### PR TITLE
Typescript port

### LINKED ISSUE #20: Types (Typescript)
# Summary

Very helpful library!
It would be crazy awesome if it had types or was migrated to typescript. 

Almost all the google sdks are typed now, or are migrating to typescript itself.

### PR DESCRIPTION
**Pull request by AverageHelper**
# Description

This is my initial attempt at porting most of the essential bits of firestore-jest-mock to TypeScript. It still feels a bit rough to me, but the overall framework is here.

This project only took me an afternoon, and if y'all think it's worth finishing, I intend to keep going.

### Breaking Changes

We exported some methods on `DocumentReference` that do not exist in Firestore proper and are really only `Query` methods. I marked these as `@deprecated` and made them throw an error indicating so. (AFAIK, no reasonable developer is likely to have abused Firestore's API like this and expected things to work, but now at least there are some real hard blocks at the testing stage in case they did.)
* We may consider removing them instead.

Mock functions are now exported through <root>/dist, rather than the <root> as before. I haven't tried this branch in any external projects yet to make sure this is how npm packages work, so that should be tested as well. If y'all have any experience with exporting TypeScript output to npm, your feedback would be appreciated.

## Related issues

Fixes #20 

## How to test

```
npm run test
```

### CODE REVIEW

**Comment by AverageHelper** [comment]
Interesting. Tests pass locally, but not in CI. I'm not sure what's going wrong here.

**Comment by AverageHelper** [comment]
I've finished typing the mocks folder. It's not particularly pretty yet, but I'd like y'alls thoughts on how the interfaces should be spelled and exported. Comments are welcome.

**Comment by AverageHelper** [comment]
This... is a large PR. I wonder if it might be easier to review this if we did only add typings incrementally, via declarations files.

**Comment by sbatson5** [comment]
Hey @AverageHelper 

Thanks again for your contributions.

I think you're right and this PR just feels too large to realistically review. I'd be too worried about unknowingly introducing breaking changes.  I feel like your first suggestion of creating `.d.ts` files for each module one at a time makes sense.  We can still wait to cut the release until all of them are in, but it at least makes it easier to review.

I'm also not a TypeScript user so it would make it easier for me when reviewing 😅

**Comment by AverageHelper** [comment]
@sbatson5 

Thanks for your feedback. I'll get onto making some `.d.ts` files, and send a smaller PR or two with those changes.

**Comment by AverageHelper** [comment]
@sbatson5 

See #78 for my initial work on exporting type declarations. More PRs will be necessary to flesh this out, but that at least sets up the bulk of the necessary boilerplate.

**Comment by AverageHelper** [comment]
@sbatson5

#90 is ready with more typings. I'm sorry it's taken me this long to come up with these. I'll have more time over the next new months to dedicate to work-related projects like this.

**Pull request closed without merging**
